#!/bin/bash
# 宿主侧包装：用官方 vLLM 0.30.0 + 运行时补丁启动 18420 Flash-Next W4A16（不 chroot）。
# 与 start-flash-next-w4a16.sh（chroot 定制镜像栈）完全独立：env / 日志 / 缓存另立。
#
# 用法：
#   bash /home/ll/deploy/vllm-0300/start-flash-next-0300.sh            # 定稿参数
#   FN_SPEC=none bash ...                                              # 关投机
#   FN_DRY_RUN=1 bash ...                                              # 只打印 argv
#   FN_FORCE=1 bash ...                                                # 跳过"显存归零"门禁
set -u
BASE=/home/ll/deploy/vllm-0300
# 启动 = 操作者声明实例应在运行：清除人工停止闩锁，恢复看门狗托管（09-26）
rm -f /home/ll/deploy/fnx-manual-stop
PORT=${FN_PORT:-18420}
LOG=${FN_LOG:-/home/ll/deploy/vllm-flash-next-0300.log}
ENVFILE=${FN_ENVFILE:-$BASE/launch.env}
RA_LOAD=${RA_LOAD:-128}
INNER=${INNER:-$BASE/bin/flash-next-0300-inner.sh}

# 1) 弹窗/手动参数落盘：透传全部 FN_*（只排除 FN_ENVFILE 自身）。
#    sudo 会清环境，只有写进 ENVFILE 的部分能进 inner —— 与旧栈同机制；
#    动态扫 FN_* 而非手写白名单（09-26 FN_GENCFG 静默失效事故的根治）。
FOUND=0
{
  echo "# generated by start-flash-next-0300.sh $(date -Is)"
  for v in $(compgen -e | grep -E '^FN_[A-Z0-9_]+$' | grep -v '^FN_ENVFILE$' | sort); do
    val=$(printenv "$v" 2>/dev/null || true)
    if [ -n "$val" ]; then printf '%s=%q\n' "$v" "$val"; FOUND=1; fi
  done
} > "$ENVFILE"
chmod 644 "$ENVFILE" 2>/dev/null || true
if [ "$FOUND" = "0" ]; then
  echo "[wrapper] $(date -Is) 未收到 FN_*，inner 用内置定稿参数" >> "$LOG"
fi

# 2) read_ahead_kb=128（全程，09-23 定版拐点值；按 by-id 定位，重启盘符互换不会打错盘）
#    【sudo 写法铁律·09-30 实锤】不要"先用 sudo -S 建时间戳、后面用 sudo -n"：sudo 的
#    时间戳在本机（无 tty 票据）不跨脚本子进程复用，实测 wrapper 里 `sudo -n` 报"需要密码"
#    而同一 ssh 会话内两条命令连续跑却能复用。⇒ 每处 sudo 都自带密码管道；且**绝不能**在
#    命令尾部加 `< /dev/null`——它会覆盖密码管道（本项目已踩两次）。要在命令内部脱离 stdin，
#    包一层 `sh -c 'exec ... </dev/null'`（sudo 先读完密码行，重定向只作用于其子进程）。
DEV2T=$(readlink -f /dev/disk/by-id/nvme-JZ-SSD2T-XW_* 2>/dev/null | head -1)
if [ -n "$DEV2T" ] && [ -e "/sys/block/$(basename "$DEV2T")/queue/read_ahead_kb" ]; then
  echo "${SUDO_PASS:?本副本已脱敏：先 export SUDO_PASS=<部署机 sudo 口令>}" | sudo -S -p '' sh -c "echo $RA_LOAD > /sys/block/$(basename "$DEV2T")/queue/read_ahead_kb" 2>/dev/null
  echo "[wrapper] read_ahead_kb=$RA_LOAD -> $(basename "$DEV2T")" >> "$LOG"
fi

# 3) 门禁：显存必须归零才允许启动（幽灵显存=启动失败第一嫌疑，旧栈铁律）
if [ "${FN_FORCE:-0}" != "1" ]; then
  BUSY=$(timeout 20 nvidia-smi --query-gpu=index,memory.used --format=csv,noheader,nounits 2>/dev/null \
         | awk -F', ' '$2 > 2000 {print $1":"$2"MiB"}' | tr '\n' ' ')
  if [ -n "$BUSY" ]; then
    echo "[wrapper] 拒绝启动：显存未归零 -> $BUSY（先跑 stop-flash-next-0300.sh / 旧栈 stop 脚本；确认无孤儿后 FN_FORCE=1 可强启）" | tee -a "$LOG"
    exit 1
  fi
fi

# 4) 启动（inner 自带锁页预检；必须 root —— ll 的 memlock 上限 64 MiB 钉不住 95.4 GiB PLE 表）
#    密码仍走管道；用 `sh -c 'exec ...</dev/null'` 让 vLLM 的 stdin 脱离管道/终端
#    （sudo 先读密码行，重定向只作用于它的子进程），setsid 保证 ssh 断开不被 SIGHUP 带走。
echo "[wrapper] $(date -Is) inner=$INNER port=$PORT envfile=$ENVFILE" >> "$LOG"
echo "${SUDO_PASS:?本副本已脱敏：先 export SUDO_PASS=<部署机 sudo 口令>}" | sudo -S -p '' sh -c "exec setsid bash \"\$1\" >> \"\$2\" 2>&1 </dev/null" _ "$INNER" "$LOG" &
disown
echo "[wrapper] 已提交启动，日志：$LOG"
