#!/bin/bash
# ---- sudo 凭据（脱敏版）----
# 生产机上 chroot 内进程属 root，宿主脚本需要 sudo。两种给法二选一：
#   A) 推荐：/etc/sudoers.d/ 配 NOPASSWD（见 docs/01-host-prep.md），无需本变量
#   B) 环境变量 SUDO_PASS 传入密码（不落盘、不写进脚本）
if [ -n "${SUDO_PASS:-}" ]; then
  SUDO() { printf '%s\n' "$SUDO_PASS" | sudo -S -p '' "$@"; }
else
  SUDO() { sudo -n "$@"; }
fi

# 宿主侧包装：从 chroot 启动 Flash-Next W4A16-AutoRound（gavinxym/170hx-2 手册方案）
# 与 start-flash-next-170hx.sh（NVFP4 栈）完全独立：env/日志/缓存另立，互不干扰。
# 用法：
#   bash start-flash-next-w4a16.sh                    # 内置缺省（手册定稿参数, 无投机）
#   FN_SPEC=mtp4 bash start-flash-next-w4a16.sh       # 加 MTP4 投机
#   FN_DRY_RUN=1 bash ...                             # inner 只打印命令
set -u
R=/media/ll/data/vllm-image/rootfs
PORT=${FN_PORT:-18420}
LOG=${FN_LOG:-/home/ll/deploy/vllm-flash-next-w4a16.log}
PROF=/home/ll/deploy/flash-next-w4a16-loadprofile.log
ENVFILE=${FN_ENVFILE:-/home/ll/deploy/flash-next-w4a16-launch.env}
RA_LOAD=${RA_LOAD:-128}

# 1) 弹窗参数落盘（仅透传显式给出的 FN_*）
FOUND=0
{
  echo "# generated by start-flash-next-w4a16.sh $(date -Is)"
  for v in FN_MODEL_PATH FN_SERVED FN_PORT FN_DTYPE FN_MAXLEN FN_GPUMEM FN_BLOCK FN_SSMDTYPE \
       FN_LONGCTX FN_1M_MODEL_PATH FN_YARN_FACTOR \
           FN_SEQS FN_MBTOKENS FN_TP FN_PP FN_PARTITION FN_MOE FN_SPEC FN_HC_GEMV FN_ASYNC \
           FN_PP1_FULL_DECODE FN_DIAG_SAMPLE \
           FN_LOG_LEVEL FN_CACHE_ROOT FN_EXTRA_ARGS FN_EXTRA_ENV FN_DRY_RUN FN_KVOFF FN_KVOFF_BYTES \
            FN_PLE_INT8 FN_PLE_LOC; do
    val=$(printenv "$v" 2>/dev/null || true)
    if [ -n "$val" ]; then printf '%s=%q\n' "$v" "$val"; FOUND=1; fi
  done
} > "$ENVFILE"
chmod 644 "$ENVFILE" 2>/dev/null || true
if [ "$FOUND" = "0" ]; then
  rm -f "$ENVFILE"
  echo "[wrapper] $(date -Is) 未收到 FN_* 参数，inner 使用内置缺省（gavinxym 手册定稿 + PLE mmap）" >> "$LOG"
fi

# 2) read_ahead_kb：全程 128 KB（实测拐点，2026-09-23 定版）
#    实测（2T 盘 2.70GB 分片、每轮 fadvise DONTNEED）：0->297 / 128->3011 / 256->3113 /
#    512->3080 / 1024->3301 / 2048->3094 / 8192->3303 MB/s。128KB 已饱和；2048 无吞吐收益
#    且缺页读放大 16x；设 0 会让权重加载慢 10.9x（475s vs 43.7s），绝不可取。
#    机制：内核对 bdi->ra_pages 在 open/mmap 时刻快照进 file->f_ra，事后改 sysfs 对已开 fd
#    无效 ⇒ "加载期高 / 服务期回落 0" 的两段式对已建立的映射不成立，只能全程取一个值。
#    持久化：/etc/udev/rules.d/99-nvme-readahead.rules（按 ENV{ID_SERIAL} 匹配，重启盘符
#    与系统盘互换也不会打错盘）。RA_LOAD=<KB> 可覆盖，但不建议用 0 或 2048。

DEV2T=$(readlink -f /dev/disk/by-id/nvme-JZ-SSD2T-XW_* 2>/dev/null | head -1)
if [ -n "$DEV2T" ] && [ -e "/sys/block/$(basename "$DEV2T")/queue/read_ahead_kb" ]; then
  SUDO sh -c "echo $RA_LOAD > /sys/block/$(basename '"$DEV2T"')/queue/read_ahead_kb" 2>/dev/null
  echo "[wrapper] read_ahead_kb=$RA_LOAD -> $(basename "$DEV2T")" >> "$LOG"
else
  echo "[wrapper] 未按 by-id 找到数据盘，跳过 read_ahead 设置" >> "$LOG"
fi
: > "$PROF"
if [ -x /home/ll/deploy/flash-next-ra-watch.sh ]; then
  setsid /home/ll/deploy/flash-next-ra-watch.sh "$PORT" >/dev/null 2>&1 &
fi

# 3) 进入 chroot 启动（此行自带 SUDO 密码管道；上方 read_ahead 行已预热 sudo 时间戳）
INNER=${INNER:-/home/ll/deploy/flash-next-w4a16-inner.sh}
echo "[wrapper] $(date -Is) inner=$INNER port=$PORT envfile=$ENVFILE" >> "$LOG"
SUDO setsid chroot $R /bin/bash "$INNER" >> "$LOG" 2>&1
